blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/agentjido/jido_action/blob/main/README.md
    about: Check the documentation for usage examples and API reference
  - name: 💬 Discussions
    url: https://github.com/agentjido/jido_action/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/agentjido/jido_action/security/advisories/new
    about: Report security vulnerabilities privately
